# Backend Dockerfile
FROM python:3.11-slim

# Variables d'environnement
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Installer les dépendances
COPY backend/requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copier le code
COPY backend/ .

# Lancer le serveur
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]